import type {
  Activity,
  CalendarEvent,
  FinanceOp,
  MaintenanceJob,
  WorkspaceContact,
  WorkspaceDocument,
  WorkspaceProperty,
} from './types';

export const properties: WorkspaceProperty[] = [
  {
    id: 'p1',
    name: 'Appartement Terreaux',
    photo: '/hero.jpg',
    address: '14 rue des Capucins, 69001 Lyon',
    city: 'Lyon',
    type: 'apartment',
    usage: 'rental',
    occupancy: 'rented',
    surface: 72,
    rooms: 3,
    bedrooms: 2,
    yearBuilt: 1978,
    estimatedValue: 318000,
    monthlyIncome: 1280,
    monthlyExpenses: 310,
    nextDue: '2026-09-05',
    nextDueLabel: 'Loyer septembre',
  },
  {
    id: 'p2',
    name: 'Maison Saint-Mitre',
    photo: '/signup.jpg',
    address: '8 allée des Pins, 13090 Aix-en-Provence',
    city: 'Aix-en-Provence',
    type: 'house',
    usage: 'rental',
    occupancy: 'rented',
    surface: 145,
    rooms: 6,
    bedrooms: 4,
    yearBuilt: 1994,
    estimatedValue: 672000,
    monthlyIncome: 2350,
    monthlyExpenses: 720,
    nextDue: '2026-09-10',
    nextDueLabel: 'Assurance habitation',
    alert: 'Diagnostic DPE à renouveler',
  },
  {
    id: 'p3',
    name: 'Studio Oberkampf',
    photo: '/hero.jpg',
    address: '52 rue de la Folie-Méricourt, 75011 Paris',
    city: 'Paris',
    type: 'studio',
    usage: 'rental',
    occupancy: 'vacant',
    surface: 28,
    rooms: 1,
    bedrooms: 0,
    yearBuilt: 1905,
    estimatedValue: 238000,
    monthlyIncome: 0,
    monthlyExpenses: 140,
    nextDue: '2026-09-18',
    nextDueLabel: 'Taxe foncière (solde)',
    alert: 'Vacant depuis 21 jours',
  },
  {
    id: 'p4',
    name: 'Longère des Chênes',
    photo: '/signup.jpg',
    address: '2 chemin du Bois, 44100 Nantes',
    city: 'Nantes',
    type: 'house',
    usage: 'personal',
    occupancy: 'personal',
    surface: 180,
    rooms: 7,
    bedrooms: 4,
    yearBuilt: 1962,
    estimatedValue: 415000,
    monthlyIncome: 0,
    monthlyExpenses: 210,
    nextDue: '2026-10-01',
    nextDueLabel: 'Entretien chaudière',
  },
];

export const series = {
  month: [
    { label: 'S1', income: 860, expense: 320 },
    { label: 'S2', income: 910, expense: 340 },
    { label: 'S3', income: 905, expense: 355 },
    { label: 'S4', income: 955, expense: 365 },
  ],
  '3m': [
    { label: 'Juin', income: 3480, expense: 1290 },
    { label: 'Juil.', income: 3510, expense: 1410 },
    { label: 'Août', income: 3630, expense: 1380 },
  ],
  '6m': [
    { label: 'Mars', income: 3420, expense: 1210 },
    { label: 'Avr.', income: 3450, expense: 1260 },
    { label: 'Mai', income: 3480, expense: 1310 },
    { label: 'Juin', income: 3480, expense: 1290 },
    { label: 'Juil.', income: 3510, expense: 1410 },
    { label: 'Août', income: 3630, expense: 1380 },
  ],
  year: [
    { label: 'S', income: 3180, expense: 1180 },
    { label: 'O', income: 3220, expense: 1210 },
    { label: 'N', income: 3250, expense: 1240 },
    { label: 'D', income: 3290, expense: 1320 },
    { label: 'J', income: 3360, expense: 1190 },
    { label: 'F', income: 3380, expense: 1220 },
    { label: 'M', income: 3420, expense: 1210 },
    { label: 'A', income: 3450, expense: 1260 },
    { label: 'M', income: 3480, expense: 1310 },
    { label: 'J', income: 3480, expense: 1290 },
    { label: 'J', income: 3510, expense: 1410 },
    { label: 'A', income: 3630, expense: 1380 },
  ],
};

export const operations: FinanceOp[] = [
  { id: 'o1', propertyId: 'p1', date: '2026-08-05', kind: 'income', category: 'Loyer', label: 'Loyer Dupont', amount: 1280 },
  { id: 'o2', propertyId: 'p2', date: '2026-08-04', kind: 'income', category: 'Loyer', label: 'Loyer Martin', amount: 2350 },
  { id: 'o3', propertyId: 'p1', date: '2026-08-08', kind: 'expense', category: 'Charges', label: 'Copropriété T3', amount: 90 },
  { id: 'o4', propertyId: 'p2', date: '2026-08-12', kind: 'expense', category: 'Crédit', label: 'Mensualité Crédit Agricole', amount: 980 },
  { id: 'o5', propertyId: 'p2', date: '2026-08-15', kind: 'expense', category: 'Travaux', label: 'Fuite toiture (acompte)', amount: 420 },
  { id: 'o6', propertyId: 'p3', date: '2026-08-18', kind: 'expense', category: 'Charges', label: 'Copropriété studio', amount: 68 },
  { id: 'o7', propertyId: 'p4', date: '2026-08-20', kind: 'expense', category: 'Assurance', label: 'MAIF habitation', amount: 47 },
  { id: 'o8', propertyId: 'p1', date: '2026-08-22', kind: 'expense', category: 'Taxe', label: 'Provision taxe foncière', amount: 85 },
];

export const documents: WorkspaceDocument[] = [
  { id: 'd1', propertyId: 'p1', title: 'Bail Dupont 2024', category: 'contrat', status: 'valid', addedAt: '2024-09-01', expiresAt: '2027-08-31' },
  { id: 'd2', propertyId: 'p2', title: 'DPE Maison Saint-Mitre', category: 'diagnostic', status: 'expiring', addedAt: '2016-03-12', expiresAt: '2026-09-30' },
  { id: 'd3', propertyId: 'p2', title: 'Assurance PNO 2026', category: 'assurance', status: 'valid', addedAt: '2026-01-10', expiresAt: '2027-01-09' },
  { id: 'd4', propertyId: 'p3', title: 'Règlement de copropriété', category: 'propriété', status: 'valid', addedAt: '2023-05-02', expiresAt: null },
  { id: 'd5', propertyId: 'p4', title: 'Attestation gaz', category: 'diagnostic', status: 'expired', addedAt: '2021-04-02', expiresAt: '2026-04-02' },
  { id: 'd6', propertyId: 'p1', title: 'Quittance août 2026', category: 'facture', status: 'valid', addedAt: '2026-08-06', expiresAt: null },
];

export const jobs: MaintenanceJob[] = [
  {
    id: 'm1',
    propertyId: 'p2',
    title: 'Reprise toiture sud',
    description: 'Tuiles glissées après orage. Devis couvreur reçu.',
    priority: 'high',
    category: 'Toiture',
    vendor: 'Toitures Calvet',
    due: '2026-09-12',
    estimate: 1860,
    actual: null,
    status: 'todo',
  },
  {
    id: 'm2',
    propertyId: 'p3',
    title: 'Rafraîchissement peintures',
    description: 'Remise en location : murs salon et entrée.',
    priority: 'medium',
    category: 'Travaux',
    vendor: 'Atelier Blanc',
    due: '2026-09-20',
    estimate: 740,
    actual: null,
    status: 'planned',
  },
  {
    id: 'm3',
    propertyId: 'p1',
    title: 'Robinetterie cuisine',
    description: 'Fuite lente signalée par le locataire.',
    priority: 'medium',
    category: 'Plomberie',
    vendor: 'Aqua Lyon',
    due: '2026-09-04',
    estimate: 180,
    actual: null,
    status: 'progress',
  },
  {
    id: 'm4',
    propertyId: 'p4',
    title: 'Entretien chaudière',
    description: 'Visite annuelle contractuelle.',
    priority: 'low',
    category: 'Chauffage',
    vendor: 'Dalkia Habitat',
    due: '2026-08-18',
    estimate: 129,
    actual: 129,
    status: 'done',
  },
];

export const events: CalendarEvent[] = [
  { id: 'e1', propertyId: 'p1', date: '2026-09-05', title: 'Loyer Dupont', kind: 'loyer' },
  { id: 'e2', propertyId: 'p2', date: '2026-09-10', title: 'Renouvellement assurance', kind: 'assurance' },
  { id: 'e3', propertyId: 'p2', date: '2026-09-12', title: 'Intervention toiture', kind: 'intervention' },
  { id: 'e4', propertyId: 'p3', date: '2026-09-18', title: 'Solde taxe foncière', kind: 'taxe' },
  { id: 'e5', propertyId: 'p4', date: '2026-10-01', title: 'Entretien chaudière', kind: 'entretien' },
  { id: 'e6', propertyId: 'p1', date: '2026-09-22', title: 'Visite DPE (option)', kind: 'visite' },
];

export const contacts: WorkspaceContact[] = [
  { id: 'c1', name: 'Claire Dupont', role: 'Locataire', email: 'c.dupont@email.com', phone: '06 12 44 81 09', propertyIds: ['p1'] },
  { id: 'c2', name: 'Julien Martin', role: 'Locataire', email: 'j.martin@email.com', phone: '06 77 20 14 55', propertyIds: ['p2'] },
  { id: 'c3', name: 'Toitures Calvet', role: 'Artisan', email: 'contact@calvet-toitures.fr', phone: '04 42 18 90 12', propertyIds: ['p2'] },
  { id: 'c4', name: 'MAIF Aix', role: 'Assureur', email: 'aix@maif.fr', phone: '04 42 27 10 10', propertyIds: ['p2', 'p4'] },
  { id: 'c5', name: 'Crédit Agricole Lyon', role: 'Banque', email: 'agence.terreaux@ca.fr', phone: '04 72 10 44 00', propertyIds: ['p1'] },
  { id: 'c6', name: 'Syndic Harmonie', role: 'Syndic', email: 'syndic@harmonie-lyon.fr', phone: '04 78 30 22 11', propertyIds: ['p1'] },
];

export const activity: Activity[] = [
  { id: 'a1', at: '2026-08-22', text: 'Provision taxe foncière enregistrée — Terreaux' },
  { id: 'a2', at: '2026-08-20', text: 'Quittance août générée — Dupont' },
  { id: 'a3', at: '2026-08-15', text: 'Acompte toiture ajouté — Saint-Mitre' },
  { id: 'a4', at: '2026-08-12', text: 'Document DPE marqué à renouveler' },
];

export const recentIds = ['p2', 'p1', 'p3'];
