/** SEO landing copy for /property-management-software-for-small-landlords. English is the canonical target. */
export const smallLandlordEn = {
  moreLabel: 'Also explore',
  relatedPmsLead: 'Need the broader operations view? See Rentelyo as',
  relatedPmsAnchor: 'property management software for landlords',
  relatedPmsTail: '.',
  relatedSimpleLead: 'Coming from spreadsheets and folders? Start with',
  relatedSimpleAnchor: 'landlord software',
  relatedSimpleTail: '.',
  hero: {
    kicker: 'For small landlords',
    h1: 'Property Management Software for Small Landlords',
    lede: 'Manage your properties, tenants, leases, rent, expenses, maintenance and documents in one simple workspace — without the complexity of enterprise property management software.',
    primary: 'Get started free',
    secondary: 'View pricing',
    note: 'No credit card required',
  },
  problem: {
    h2: 'You shouldn’t need enterprise software to manage a few rentals',
    body: 'A small landlord still has real operational work: properties, tenants, lease dates, expected rent, late payments, expenses, repairs and documents. Many professional systems add team workflows and organisational layers meant for larger operations. Rentelyo keeps the essentials connected — everything you need to manage your rentals, none of the enterprise complexity.',
    needs: [
      'Properties',
      'Tenants',
      'Lease dates',
      'Expected rent',
      'Late payments',
      'Expenses',
      'Repairs',
      'Documents',
    ],
  },
  essentials: {
    h2: 'The essentials for managing your rental portfolio',
    lede: 'These are the operational tools a self-managing landlord actually uses — not a department-scale process map.',
    cards: [
      { title: 'Properties', body: 'Keep property information organized.' },
      { title: 'Tenants', body: 'Keep tenant records and contact details together.' },
      { title: 'Leases', body: 'Track lease terms, dates, rent, charges and important deadlines.' },
      { title: 'Rent', body: 'Know what’s expected, paid, pending or late.' },
      { title: 'Expenses', body: 'Record costs against the right property.' },
      { title: 'Maintenance', body: 'Track jobs, priority, provider, status and cost.' },
      { title: 'Documents', body: 'Store files securely and keep them with the right records.' },
    ],
  },
  chain: {
    h2: 'From property to payment, keep everything connected',
    lede: 'Each record feeds the next, so you are not reconstructing the story from separate files when a date, payment or document is needed.',
    steps: [
      { title: 'Property', body: 'Add the rental and keep its details in one record.' },
      { title: 'Tenant', body: 'Store contact details and link the person to that property.' },
      { title: 'Lease', body: 'Record dates, rent, charges, deposit and payment frequency on the same lease.' },
      { title: 'Expected rent', body: 'Active leases generate the periods you should receive.' },
      { title: 'Payment status', body: 'Record each payment as Paid, Pending, Late or Partial.' },
      { title: 'Receipt', body: 'When rent is marked paid, generate a PDF receipt and email it.' },
    ],
    sideTitle: 'Alongside the same workspace',
    side: [
      { title: 'Expenses', body: 'Log amount, date, category, vendor and property.' },
      { title: 'Maintenance', body: 'Track priority, status, vendor and cost — then convert a cost into an expense.' },
      { title: 'Documents', body: 'Upload files and associate them with the property, tenant or lease they belong to.' },
    ],
  },
  rent: {
    h2: 'Know where every rent payment stands',
    body: 'Rentelyo tracks rent in the workspace. You record payments yourself; the product does not process tenant rent payments.',
    points: [
      'Expected rent periods generated from active leases',
      'Paid, Pending, Late and Partial statuses',
      'Payment history on each period',
      'Upcoming and overdue reminders',
      'PDF rent receipts, with the option to email them',
    ],
  },
  leases: {
    h2: 'Keep lease dates from becoming surprises',
    body: 'Lease records hold the dates and amounts you need to act on. Increases are tracked and applied only after you confirm them. Rentelyo does not auto-renew leases or collect e-signatures.',
    points: [
      'Start and end dates',
      'Rent, charges and deposit',
      'Payment frequency',
      'Lease expiry alerts',
      'Rent-review tracking, with increases applied after you confirm',
    ],
  },
  costs: {
    h2: 'Understand the day-to-day costs of your rentals',
    expensesTitle: 'Expenses',
    expensesBody: 'See what each property is costing you without a separate cost workbook.',
    expensesPoints: ['Property', 'Category', 'Vendor', 'Amount', 'Date', 'Description', 'Totals'],
    maintenanceTitle: 'Maintenance',
    maintenanceBody: 'Record the work you arrange as the landlord. Tenants do not submit requests in Rentelyo.',
    maintenancePoints: ['Property', 'Priority', 'Status', 'Vendor', 'Cost', 'Convert cost into an expense'],
  },
  documents: {
    h2: 'Keep important rental documents where they belong',
    body: 'Upload the files you already have. Rentelyo stores them securely next to the rental they belong to. It does not generate leases or collect electronic signatures.',
    points: [
      'Secure upload',
      'Categories',
      'Association with a property',
      'Optional association with a tenant',
      'Optional association with a lease',
      'Download or delete when needed',
    ],
  },
  dashboard: {
    h2: 'See the health of your rentals at a glance',
    body: 'The dashboard is operational visibility — how many properties you have, which are rented, and where rent and costs stand. It is not valuation, yield or tax accounting.',
    metrics: [
      'Total properties',
      'Rented and available',
      'Expected rent',
      'Collected',
      'Pending',
      'Overdue',
      'Expenses',
      'Net cash flow',
    ],
  },
  fit: {
    h2: 'Built for landlords, not property-management departments',
    body: 'Different users need different tools. A self-managing landlord usually does not need the organisational layers built for larger operations.',
    leftTitle: 'Complexity a small landlord may not need',
    left: [
      'Large team workflows',
      'Complex organisational structures',
      'Enterprise processes',
      'Unnecessary administrative layers',
    ],
    rightTitle: 'What Rentelyo gives you',
    right: [
      'Property records',
      'Tenant records',
      'Leases',
      'Rent tracking',
      'Expenses',
      'Maintenance',
      'Documents',
      'Reminders',
      'A clear dashboard',
    ],
  },
  grow: {
    h2: 'Start with your first property. Grow when you need to.',
    body: 'Begin on the free plan with one property and one tenant. When the portfolio grows, paid plans raise those limits: Smart currently covers up to five properties, Premium up to fifteen. Always check the pricing page for the current configuration.',
    plan: 'No credit card to start. Move to a paid plan only when you need more room.',
    cta: 'View pricing',
  },
  why: {
    h2: 'Why small landlords use software',
    items: [
      {
        title: 'Stay organized',
        body: 'Find the property, the person and the file without opening three different places.',
      },
      {
        title: 'Catch important deadlines',
        body: 'Lease expiry and upcoming or overdue rent stay visible, so dates are less likely to slip.',
      },
      {
        title: 'Understand rental cash flow',
        body: 'See expected rent, what came in, what is late and what each property cost — operational figures, not forecasts.',
      },
      {
        title: 'Keep records in one place',
        body: 'Leases, receipts, invoices and proofs sit next to the rental they belong to.',
      },
    ],
  },
  faq: {
    h2: 'Frequently asked questions',
    items: [
      {
        q: 'What is property management software for small landlords?',
        a: 'It is software that helps self-managing landlords run a small rental portfolio: property records, tenants, leases, rent tracking, expenses, maintenance and documents, without the process layers of an enterprise property-management system.',
      },
      {
        q: 'Who is Rentelyo designed for?',
        a: 'Rentelyo is designed for independent landlords who already have properties and tenants and want to manage operations themselves. It is not built as a platform for large property-management departments, agencies or teams.',
      },
      {
        q: 'Is Rentelyo suitable for landlords with only one property?',
        a: 'Yes. The free plan currently includes one property and one tenant, so you can organise a single rental without paying first. Paid plans increase those limits when the portfolio grows.',
      },
      {
        q: 'Can I manage multiple properties with Rentelyo?',
        a: 'Yes, within your plan. Smart currently covers up to five properties. Premium currently covers up to fifteen. Exact limits are always listed on the pricing page.',
      },
      {
        q: 'Can I manage tenants and leases?',
        a: 'Yes. You can keep tenant contact details, associate tenants with properties, and record leases with start and end dates, rent, charges, deposits and payment frequency.',
      },
      {
        q: 'Does Rentelyo automatically track expected rent?',
        a: 'Yes. Active leases generate expected rent periods. You then record each payment and follow its status in the workspace.',
      },
      {
        q: 'Can Rentelyo identify late rent?',
        a: 'Yes. Each expected period can show as Paid, Pending, Late or Partial, so overdue rent stays visible instead of sitting in a forgotten spreadsheet row.',
      },
      {
        q: 'Does Rentelyo collect tenant rent online?',
        a: 'No. Rentelyo currently helps landlords track and record rent payments. It does not process tenant rent payments online.',
      },
      {
        q: 'Can I track rental property expenses?',
        a: 'Yes. Record amount, date, category, vendor, description and the related property, then follow expense totals.',
      },
      {
        q: 'Can I manage property maintenance?',
        a: 'Yes. Create a maintenance record for a property with priority, status, vendor and cost, and convert a cost into an expense. Landlords enter these jobs — there is no tenant request portal.',
      },
      {
        q: 'Can I store rental documents?',
        a: 'Yes. Upload files securely, categorise them, associate them with a property, and optionally with a tenant or lease, then download or delete them. Rentelyo does not offer e-signature or generated leases.',
      },
      {
        q: 'Can Rentelyo generate PDF rent receipts?',
        a: 'Yes. When rent is marked as paid, you can generate a PDF rent receipt and email it.',
      },
      {
        q: 'Do I need property management software if I only own a few rentals?',
        a: 'You may not need an enterprise system. A few rentals still produce lease dates, expected rent, expenses, repairs and files. Rentelyo is meant to keep that operational work connected without adding department-scale process.',
      },
      {
        q: 'Is Rentelyo a property listing website?',
        a: 'No. Rentelyo is property management software for landlords who already have tenants. It is not a listing website, marketplace or tenant-acquisition service.',
      },
    ],
  },
  finalCta: {
    h2: 'Simple property management for your rental portfolio',
    body: 'Keep your properties, tenants, leases, rent and rental records organized without unnecessary complexity.',
    primary: 'Get started free',
    secondary: 'View pricing',
  },
};

export const smallLandlordFr: typeof smallLandlordEn = {
  moreLabel: 'À explorer aussi',
  relatedPmsLead: 'Vous voulez la vue opérationnelle plus large ? Découvrez Rentelyo comme',
  relatedPmsAnchor: 'logiciel de gestion locative pour propriétaires',
  relatedPmsTail: '.',
  relatedSimpleLead: 'Vous partez de tableurs et de dossiers ? Commencez par le',
  relatedSimpleAnchor: 'logiciel pour propriétaires',
  relatedSimpleTail: '.',
  hero: {
    kicker: 'Pour les petits propriétaires',
    h1: 'Logiciel de gestion locative pour petits propriétaires',
    lede: 'Gérez biens, locataires, baux, loyers, dépenses, entretien et documents dans un espace simple — sans la complexité des logiciels d’entreprise.',
    primary: 'Commencer gratuitement',
    secondary: 'Voir les tarifs',
    note: 'Sans carte bancaire',
  },
  problem: {
    h2: 'Pas besoin d’un logiciel d’entreprise pour quelques locations',
    body: 'Un petit bailleur a quand même un vrai travail opérationnel : biens, locataires, dates de bail, loyers attendus, retards, dépenses, réparations et documents. Beaucoup d’outils professionnels ajoutent des processus d’équipe pensés pour de plus grandes structures. Rentelyo relie l’essentiel : tout ce qu’il faut pour gérer vos locations, sans la complexité d’entreprise.',
    needs: ['Biens', 'Locataires', 'Dates de bail', 'Loyers attendus', 'Retards', 'Dépenses', 'Réparations', 'Documents'],
  },
  essentials: {
    h2: 'L’essentiel pour gérer votre portefeuille locatif',
    lede: 'Ce sont les outils qu’un bailleur indépendant utilise vraiment — pas une carte de processus d’un service entier.',
    cards: [
      { title: 'Biens', body: 'Gardez les informations de chaque location en ordre.' },
      { title: 'Locataires', body: 'Réunissez fiches et coordonnées au même endroit.' },
      { title: 'Baux', body: 'Suivez conditions, dates, loyer, charges et échéances.' },
      { title: 'Loyers', body: 'Voyez ce qui est attendu, payé, en attente ou en retard.' },
      { title: 'Dépenses', body: 'Enregistrez chaque coût sur le bon bien.' },
      { title: 'Entretien', body: 'Suivez travaux, priorité, prestataire, statut et coût.' },
      { title: 'Documents', body: 'Stockez les fichiers et rattachez-les aux bonnes fiches.' },
    ],
  },
  chain: {
    h2: 'Du bien au paiement, tout reste relié',
    lede: 'Chaque fiche alimente la suivante, sans reconstruire l’histoire à partir de fichiers séparés.',
    steps: [
      { title: 'Bien', body: 'Ajoutez la location et gardez ses détails dans une fiche.' },
      { title: 'Locataire', body: 'Enregistrez les coordonnées et reliez la personne à ce bien.' },
      { title: 'Bail', body: 'Notez dates, loyer, charges, dépôt et fréquence sur le même bail.' },
      { title: 'Loyer attendu', body: 'Les baux actifs créent les périodes à encaisser.' },
      { title: 'Statut de paiement', body: 'Marquez Payé, En attente, En retard ou Partiel.' },
      { title: 'Quittance', body: 'Lorsque le loyer est payé, générez une quittance PDF et envoyez-la.' },
    ],
    sideTitle: 'Dans le même espace',
    side: [
      { title: 'Dépenses', body: 'Montant, date, catégorie, prestataire et bien.' },
      { title: 'Entretien', body: 'Priorité, statut, prestataire et coût — puis conversion en dépense.' },
      { title: 'Documents', body: 'Téléversez et rattachez les fichiers au bien, locataire ou bail.' },
    ],
  },
  rent: {
    h2: 'Sachez où en est chaque loyer',
    body: 'Rentelyo suit les loyers dans l’espace de travail. Vous enregistrez les paiements ; le produit n’encaisse pas les locataires.',
    points: [
      'Périodes attendues créées depuis les baux actifs',
      'Statuts Payé, En attente, En retard et Partiel',
      'Historique de chaque période',
      'Rappels à venir et en retard',
      'Quittances PDF, avec envoi par e-mail',
    ],
  },
  leases: {
    h2: 'Évitez que les dates de bail deviennent des surprises',
    body: 'Le bail porte les dates et montants à surveiller. Les hausses sont suivies et appliquées seulement après votre confirmation. Rentelyo ne renouvelle pas automatiquement et ne collecte pas de signature électronique.',
    points: [
      'Dates de début et de fin',
      'Loyer, charges et dépôt',
      'Fréquence de paiement',
      'Alertes d’échéance',
      'Suivi des révisions, appliquées après confirmation',
    ],
  },
  costs: {
    h2: 'Comprenez le coût quotidien de vos locations',
    expensesTitle: 'Dépenses',
    expensesBody: 'Voyez ce que coûte chaque bien, sans un second classeur.',
    expensesPoints: ['Bien', 'Catégorie', 'Prestataire', 'Montant', 'Date', 'Description', 'Totaux'],
    maintenanceTitle: 'Entretien',
    maintenanceBody: 'Enregistrez les travaux que vous organisez. Les locataires ne déposent pas de demandes dans Rentelyo.',
    maintenancePoints: ['Bien', 'Priorité', 'Statut', 'Prestataire', 'Coût', 'Convertir le coût en dépense'],
  },
  documents: {
    h2: 'Gardez les documents locatifs à leur place',
    body: 'Téléversez les fichiers que vous avez déjà. Rentelyo les stocke près de la location concernée. Il ne génère pas de baux et ne collecte pas de signatures électroniques.',
    points: [
      'Téléversement sécurisé',
      'Catégories',
      'Rattachement à un bien',
      'Rattachement optionnel à un locataire',
      'Rattachement optionnel à un bail',
      'Téléchargement ou suppression',
    ],
  },
  dashboard: {
    h2: 'Voyez l’état de vos locations d’un coup d’œil',
    body: 'Le tableau de bord est une visibilité opérationnelle : nombre de biens, occupation, loyers et coûts. Ce n’est ni une valorisation, ni un rendement, ni une comptabilité fiscale.',
    metrics: [
      'Total des biens',
      'Loués et disponibles',
      'Loyers attendus',
      'Encaissés',
      'En attente',
      'En retard',
      'Dépenses',
      'Flux net',
    ],
  },
  fit: {
    h2: 'Conçu pour les propriétaires, pas pour un service de gestion',
    body: 'Les besoins diffèrent. Un bailleur qui gère seul n’a généralement pas besoin des couches organisationnelles prévues pour de plus grandes structures.',
    leftTitle: 'Une complexité souvent inutile',
    left: [
      'Processus d’équipes nombreuses',
      'Structures organisationnelles complexes',
      'Processus d’entreprise',
      'Couches administratives superflues',
    ],
    rightTitle: 'Ce que Rentelyo vous donne',
    right: [
      'Fiches de biens',
      'Fiches locataires',
      'Baux',
      'Suivi des loyers',
      'Dépenses',
      'Entretien',
      'Documents',
      'Rappels',
      'Un tableau de bord lisible',
    ],
  },
  grow: {
    h2: 'Commencez par un bien. Élargissez quand il le faut.',
    body: 'L’offre gratuite inclut un bien et un locataire. Ensuite, Smart va aujourd’hui jusqu’à cinq biens, Premium jusqu’à quinze. Vérifiez toujours la page tarifs pour la configuration en vigueur.',
    plan: 'Sans carte pour commencer. Passez à une offre payante seulement si vous avez besoin de plus de place.',
    cta: 'Voir les tarifs',
  },
  why: {
    h2: 'Pourquoi un petit bailleur utilise un logiciel',
    items: [
      { title: 'Rester organisé', body: 'Retrouver le bien, la personne et le fichier sans ouvrir trois endroits.' },
      { title: 'Ne pas rater les échéances', body: 'Fins de bail et loyers à venir ou en retard restent visibles.' },
      { title: 'Lire le flux locatif', body: 'Voyez l’attendu, l’encaissé, le retard et le coût de chaque bien — des chiffres opérationnels, pas des prévisions.' },
      { title: 'Tout au même endroit', body: 'Baux, quittances, factures et justificatifs restent près de la location concernée.' },
    ],
  },
  faq: {
    h2: 'Questions fréquentes',
    items: [
      {
        q: 'Qu’est-ce qu’un logiciel de gestion locative pour petits propriétaires ?',
        a: 'C’est un outil qui aide les bailleurs indépendants à faire tourner un petit portefeuille : biens, locataires, baux, suivi des loyers, dépenses, entretien et documents, sans les couches d’un logiciel d’entreprise.',
      },
      {
        q: 'À qui s’adresse Rentelyo ?',
        a: 'Aux propriétaires indépendants qui ont déjà des biens et des locataires et veulent gérer eux-mêmes. Ce n’est pas une plateforme pour un service de gestion, une agence ou une équipe.',
      },
      {
        q: 'Rentelyo convient-il avec un seul bien ?',
        a: 'Oui. L’offre gratuite inclut aujourd’hui un bien et un locataire. Les offres payantes augmentent ces limites si le portefeuille grandit.',
      },
      {
        q: 'Puis-je gérer plusieurs biens avec Rentelyo ?',
        a: 'Oui, dans la limite de votre formule. Smart va aujourd’hui jusqu’à cinq biens, Premium jusqu’à quinze. Les limites exactes sont sur la page tarifs.',
      },
      {
        q: 'Puis-je gérer locataires et baux ?',
        a: 'Oui. Vous conservez les coordonnées, associez les locataires aux biens, et enregistrez les baux avec dates, loyer, charges, dépôt et fréquence.',
      },
      {
        q: 'Rentelyo suit-il automatiquement les loyers attendus ?',
        a: 'Oui. Les baux actifs créent les périodes attendues. Vous enregistrez ensuite chaque paiement et suivez son statut.',
      },
      {
        q: 'Rentelyo permet-il de voir les loyers en retard ?',
        a: 'Oui. Chaque période peut être Payé, En attente, En retard ou Partiel, pour que les impayés restent visibles.',
      },
      {
        q: 'Rentelyo encaisse-t-il les loyers des locataires en ligne ?',
        a: 'Non. Rentelyo aide actuellement à suivre et enregistrer les paiements. Il n’encaisse pas les loyers en ligne.',
      },
      {
        q: 'Puis-je suivre les dépenses d’un bien ?',
        a: 'Oui. Enregistrez montant, date, catégorie, prestataire, description et bien, puis suivez les totaux.',
      },
      {
        q: 'Puis-je gérer l’entretien ?',
        a: 'Oui. Créez une fiche liée à un bien, avec priorité, statut, prestataire et coût, puis convertissez un coût en dépense. C’est le propriétaire qui saisit ces travaux.',
      },
      {
        q: 'Puis-je stocker des documents locatifs ?',
        a: 'Oui. Téléversez, classez, rattachez à un bien et éventuellement à un locataire ou un bail, puis téléchargez ou supprimez. Pas de signature électronique ni de baux générés.',
      },
      {
        q: 'Rentelyo peut-il générer des quittances PDF ?',
        a: 'Oui. Lorsque le loyer est marqué payé, vous pouvez générer une quittance PDF et l’envoyer par e-mail.',
      },
      {
        q: 'Faut-il un logiciel si je n’ai que quelques locations ?',
        a: 'Pas forcément un système d’entreprise. Quelques locations produisent déjà des dates, des loyers attendus, des dépenses, des réparations et des fichiers. Rentelyo relie ce travail sans ajouter de process de service.',
      },
      {
        q: 'Rentelyo est-il un site d’annonces ?',
        a: 'Non. C’est un logiciel de gestion locative pour propriétaires qui ont déjà des locataires. Pas d’annonces, pas de place de marché, pas de recherche de locataires.',
      },
    ],
  },
  finalCta: {
    h2: 'Une gestion locative simple pour votre portefeuille',
    body: 'Gardez biens, locataires, baux, loyers et dossiers organisés, sans complexité inutile.',
    primary: 'Commencer gratuitement',
    secondary: 'Voir les tarifs',
  },
};

export const smallLandlordEs: typeof smallLandlordEn = {
  moreLabel: 'También puede ver',
  relatedPmsLead: '¿Quiere la visión operativa más amplia? Vea Rentelyo como',
  relatedPmsAnchor: 'software de gestión de alquileres para propietarios',
  relatedPmsTail: '.',
  relatedSimpleLead: '¿Viene de hojas y carpetas? Empiece por el',
  relatedSimpleAnchor: 'software para propietarios',
  relatedSimpleTail: '.',
  hero: {
    kicker: 'Para pequeños propietarios',
    h1: 'Software de gestión de alquileres para pequeños propietarios',
    lede: 'Gestione inmuebles, inquilinos, contratos, rentas, gastos, mantenimiento y documentos en un espacio sencillo, sin la complejidad del software empresarial.',
    primary: 'Empezar gratis',
    secondary: 'Ver precios',
    note: 'Sin tarjeta de crédito',
  },
  problem: {
    h2: 'No hace falta un software de empresa para unos pocos alquileres',
    body: 'Un propietario pequeño sigue teniendo trabajo real: inmuebles, inquilinos, fechas de contrato, renta esperada, atrasos, gastos, reparaciones y documentos. Muchos sistemas profesionales añaden flujos de equipo pensados para operaciones mayores. Rentelyo conecta lo esencial: todo lo necesario para gestionar sus alquileres, sin la complejidad empresarial.',
    needs: ['Inmuebles', 'Inquilinos', 'Fechas de contrato', 'Renta esperada', 'Atrasos', 'Gastos', 'Reparaciones', 'Documentos'],
  },
  essentials: {
    h2: 'Lo esencial para gestionar su cartera de alquiler',
    lede: 'Son las herramientas que un propietario que se gestiona solo realmente usa, no un mapa de procesos de un departamento.',
    cards: [
      { title: 'Inmuebles', body: 'Mantenga organizada la información de cada alquiler.' },
      { title: 'Inquilinos', body: 'Reúna fichas y datos de contacto.' },
      { title: 'Contratos', body: 'Siga plazos, fechas, renta, gastos y vencimientos.' },
      { title: 'Renta', body: 'Sepa qué está esperado, pagado, pendiente o atrasado.' },
      { title: 'Gastos', body: 'Anote cada coste en el inmueble correcto.' },
      { title: 'Mantenimiento', body: 'Siga trabajos, prioridad, proveedor, estado y coste.' },
      { title: 'Documentos', body: 'Guarde archivos y asócielos a las fichas correctas.' },
    ],
  },
  chain: {
    h2: 'Del inmueble al pago, todo conectado',
    lede: 'Cada ficha alimenta la siguiente, sin reconstruir la historia desde archivos sueltos.',
    steps: [
      { title: 'Inmueble', body: 'Añada el alquiler y conserve sus datos en una ficha.' },
      { title: 'Inquilino', body: 'Guarde el contacto y vincule a la persona con ese inmueble.' },
      { title: 'Contrato', body: 'Registre fechas, renta, gastos, fianza y frecuencia en el mismo contrato.' },
      { title: 'Renta esperada', body: 'Los contratos activos generan los periodos a cobrar.' },
      { title: 'Estado del pago', body: 'Marque Pagado, Pendiente, Atrasado o Parcial.' },
      { title: 'Recibo', body: 'Cuando la renta está pagada, genere un PDF y envíelo.' },
    ],
    sideTitle: 'En el mismo espacio',
    side: [
      { title: 'Gastos', body: 'Importe, fecha, categoría, proveedor e inmueble.' },
      { title: 'Mantenimiento', body: 'Prioridad, estado, proveedor y coste; luego convierta el coste en gasto.' },
      { title: 'Documentos', body: 'Suba archivos y asócielos al inmueble, inquilino o contrato.' },
    ],
  },
  rent: {
    h2: 'Sepa en qué punto está cada renta',
    body: 'Rentelyo hace el seguimiento de la renta en el espacio de trabajo. Usted registra los pagos; el producto no procesa los pagos de los inquilinos.',
    points: [
      'Periodos esperados desde contratos activos',
      'Estados Pagado, Pendiente, Atrasado y Parcial',
      'Historial de cada periodo',
      'Recordatorios próximos y atrasados',
      'Recibos PDF, con opción de enviarlos por correo',
    ],
  },
  leases: {
    h2: 'Que las fechas de contrato no sean una sorpresa',
    body: 'El contrato guarda las fechas y importes a vigilar. Las subidas se siguen y se aplican solo tras su confirmación. Rentelyo no renueva automáticamente ni recoge firmas electrónicas.',
    points: [
      'Fechas de inicio y fin',
      'Renta, gastos y fianza',
      'Frecuencia de pago',
      'Alertas de vencimiento',
      'Seguimiento de revisiones, aplicadas tras confirmar',
    ],
  },
  costs: {
    h2: 'Entienda el coste diario de sus alquileres',
    expensesTitle: 'Gastos',
    expensesBody: 'Vea lo que cuesta cada inmueble, sin un segundo libro de costes.',
    expensesPoints: ['Inmueble', 'Categoría', 'Proveedor', 'Importe', 'Fecha', 'Descripción', 'Totales'],
    maintenanceTitle: 'Mantenimiento',
    maintenanceBody: 'Registre los trabajos que organiza usted. Los inquilinos no envían solicitudes en Rentelyo.',
    maintenancePoints: ['Inmueble', 'Prioridad', 'Estado', 'Proveedor', 'Coste', 'Convertir el coste en gasto'],
  },
  documents: {
    h2: 'Guarde los documentos de alquiler donde correspondan',
    body: 'Suba los archivos que ya tiene. Rentelyo los guarda junto al alquiler. No genera contratos ni recoge firmas electrónicas.',
    points: [
      'Carga segura',
      'Categorías',
      'Asociación a un inmueble',
      'Asociación opcional a un inquilino',
      'Asociación opcional a un contrato',
      'Descargar o eliminar',
    ],
  },
  dashboard: {
    h2: 'Vea la salud de sus alquileres de un vistazo',
    body: 'El panel es visibilidad operativa: cuántos inmuebles tiene, cuáles están alquilados y dónde están rentas y costes. No es valoración, rentabilidad ni fiscalidad.',
    metrics: [
      'Total de inmuebles',
      'Alquilados y disponibles',
      'Renta esperada',
      'Cobrada',
      'Pendiente',
      'Atrasada',
      'Gastos',
      'Flujo neto',
    ],
  },
  fit: {
    h2: 'Hecho para propietarios, no para un departamento de gestión',
    body: 'Cada usuario necesita herramientas distintas. Quien se gestiona solo no suele necesitar las capas organizativas de operaciones mayores.',
    leftTitle: 'Complejidad que quizá no necesite',
    left: [
      'Flujos de equipos grandes',
      'Estructuras organizativas complejas',
      'Procesos de empresa',
      'Capas administrativas innecesarias',
    ],
    rightTitle: 'Lo que le da Rentelyo',
    right: [
      'Fichas de inmuebles',
      'Fichas de inquilinos',
      'Contratos',
      'Seguimiento de rentas',
      'Gastos',
      'Mantenimiento',
      'Documentos',
      'Recordatorios',
      'Un panel claro',
    ],
  },
  grow: {
    h2: 'Empiece con su primer inmueble. Crezca cuando lo necesite.',
    body: 'El plan gratuito incluye un inmueble y un inquilino. Luego, Smart cubre hoy hasta cinco inmuebles y Premium hasta quince. Consulte siempre la página de precios para la configuración vigente.',
    plan: 'Sin tarjeta para empezar. Pase a un plan de pago solo cuando necesite más espacio.',
    cta: 'Ver precios',
  },
  why: {
    h2: 'Por qué un pequeño propietario usa software',
    items: [
      { title: 'Mantenerse organizado', body: 'Encuentre el inmueble, la persona y el archivo sin abrir tres sitios.' },
      { title: 'Pillar los plazos', body: 'Vencimientos de contrato y rentas próximas o atrasadas siguen visibles.' },
      { title: 'Entender el flujo del alquiler', body: 'Vea lo esperado, lo cobrado, lo atrasado y el coste de cada inmueble: cifras operativas, no previsiones.' },
      { title: 'Registros en un solo sitio', body: 'Contratos, recibos, facturas y justificantes junto al alquiler.' },
    ],
  },
  faq: {
    h2: 'Preguntas frecuentes',
    items: [
      {
        q: '¿Qué es el software de gestión de alquileres para pequeños propietarios?',
        a: 'Es una herramienta que ayuda a propietarios que se gestionan solos a llevar una cartera pequeña: inmuebles, inquilinos, contratos, seguimiento de rentas, gastos, mantenimiento y documentos, sin las capas de un sistema empresarial.',
      },
      {
        q: '¿Para quién está pensado Rentelyo?',
        a: 'Para propietarios independientes que ya tienen inmuebles e inquilinos y quieren gestionar ellos. No es una plataforma para un departamento de gestión, una agencia o un equipo.',
      },
      {
        q: '¿Sirve Rentelyo con un solo inmueble?',
        a: 'Sí. El plan gratuito incluye hoy un inmueble y un inquilino. Los planes de pago aumentan esos límites si crece la cartera.',
      },
      {
        q: '¿Puedo gestionar varios inmuebles con Rentelyo?',
        a: 'Sí, dentro de su plan. Smart cubre hoy hasta cinco inmuebles; Premium hasta quince. Los límites exactos están en la página de precios.',
      },
      {
        q: '¿Puedo gestionar inquilinos y contratos?',
        a: 'Sí. Conserve contactos, asocie inquilinos a inmuebles y registre contratos con fechas, renta, gastos, fianza y frecuencia.',
      },
      {
        q: '¿Rentelyo sigue automáticamente la renta esperada?',
        a: 'Sí. Los contratos activos generan periodos esperados. Usted registra cada pago y sigue su estado.',
      },
      {
        q: '¿Rentelyo identifica la renta atrasada?',
        a: 'Sí. Cada periodo puede ser Pagado, Pendiente, Atrasado o Parcial, para que los atrasos no se pierdan.',
      },
      {
        q: '¿Rentelyo cobra la renta del inquilino en línea?',
        a: 'No. Rentelyo ayuda actualmente a seguir y registrar los pagos. No procesa los pagos de los inquilinos en línea.',
      },
      {
        q: '¿Puedo registrar los gastos del inmueble?',
        a: 'Sí. Anote importe, fecha, categoría, proveedor, descripción e inmueble, y siga los totales.',
      },
      {
        q: '¿Puedo gestionar el mantenimiento?',
        a: 'Sí. Cree un registro con prioridad, estado, proveedor y coste, y convierta un coste en gasto. El propietario introduce estos trabajos.',
      },
      {
        q: '¿Puedo guardar documentos de alquiler?',
        a: 'Sí. Súbalos, clasifíquelos, asócielos a un inmueble y, si quiere, a un inquilino o contrato. No hay firma electrónica ni contratos generados.',
      },
      {
        q: '¿Rentelyo puede generar recibos PDF?',
        a: 'Sí. Cuando la renta se marca como pagada, puede generar un recibo PDF y enviarlo por correo.',
      },
      {
        q: '¿Necesito software si solo tengo unos pocos alquileres?',
        a: 'Quizá no un sistema de empresa. Unos pocos alquileres ya generan fechas, renta esperada, gastos, reparaciones y archivos. Rentelyo conecta ese trabajo sin añadir procesos de departamento.',
      },
      {
        q: '¿Rentelyo es un portal de anuncios?',
        a: 'No. Es software de gestión para propietarios que ya tienen inquilinos. No es un sitio de anuncios, un marketplace ni un servicio para captar inquilinos.',
      },
    ],
  },
  finalCta: {
    h2: 'Gestión de alquileres simple para su cartera',
    body: 'Mantenga inmuebles, inquilinos, contratos, rentas y registros organizados, sin complejidad innecesaria.',
    primary: 'Empezar gratis',
    secondary: 'Ver precios',
  },
};

export const smallLandlordDe: typeof smallLandlordEn = {
  moreLabel: 'Auch ansehen',
  relatedPmsLead: 'Sie wollen den weiteren Betriebsblick? Entdecken Sie Rentelyo als',
  relatedPmsAnchor: 'Immobilienverwaltungssoftware für Vermieter',
  relatedPmsTail: '.',
  relatedSimpleLead: 'Sie kommen von Tabellen und Ordnern? Starten Sie mit',
  relatedSimpleAnchor: 'Vermieter-Software',
  relatedSimpleTail: '.',
  hero: {
    kicker: 'Für kleine Vermieter',
    h1: 'Immobilienverwaltung für kleine Vermieter',
    lede: 'Verwalten Sie Objekte, Mieter, Verträge, Miete, Ausgaben, Instandhaltung und Dokumente in einem klaren Arbeitsbereich — ohne die Komplexität von Unternehmenssoftware.',
    primary: 'Kostenlos starten',
    secondary: 'Preise ansehen',
    note: 'Keine Kreditkarte erforderlich',
  },
  problem: {
    h2: 'Für ein paar Vermietungen brauchen Sie keine Unternehmenssoftware',
    body: 'Auch ein kleiner Vermieter hat echte Arbeit: Objekte, Mieter, Vertragsdaten, erwartete Miete, Verspätungen, Ausgaben, Reparaturen und Dokumente. Viele professionelle Systeme bringen Teamprozesse mit, die für größere Betriebe gedacht sind. Rentelyo verbindet das Wesentliche — alles für Ihre Vermietung, ohne Unternehmenskomplexität.',
    needs: ['Objekte', 'Mieter', 'Vertragsdaten', 'Erwartete Miete', 'Verspätungen', 'Ausgaben', 'Reparaturen', 'Dokumente'],
  },
  essentials: {
    h2: 'Das Wesentliche für Ihr Mietportfolio',
    lede: 'Das sind die Werkzeuge, die selbst verwaltende Vermieter wirklich nutzen — keine Prozesslandkarte einer Abteilung.',
    cards: [
      { title: 'Objekte', body: 'Objektdaten übersichtlich halten.' },
      { title: 'Mieter', body: 'Datensätze und Kontakte zusammenhalten.' },
      { title: 'Verträge', body: 'Konditionen, Daten, Miete, Nebenkosten und Fristen verfolgen.' },
      { title: 'Miete', body: 'Sehen, was erwartet, bezahlt, ausstehend oder verspätet ist.' },
      { title: 'Ausgaben', body: 'Kosten dem richtigen Objekt zuordnen.' },
      { title: 'Instandhaltung', body: 'Aufträge, Priorität, Anbieter, Status und Kosten verfolgen.' },
      { title: 'Dokumente', body: 'Dateien sicher ablegen und den richtigen Datensätzen zuordnen.' },
    ],
  },
  chain: {
    h2: 'Vom Objekt zur Zahlung bleibt alles verbunden',
    lede: 'Jeder Datensatz speist den nächsten, statt die Geschichte aus getrennten Dateien zusammenzusetzen.',
    steps: [
      { title: 'Objekt', body: 'Legen Sie die Vermietung an und halten Sie die Angaben in einem Datensatz.' },
      { title: 'Mieter', body: 'Speichern Sie Kontakte und verknüpfen Sie die Person mit dem Objekt.' },
      { title: 'Vertrag', body: 'Daten, Miete, Nebenkosten, Kaution und Rhythmus am selben Vertrag.' },
      { title: 'Erwartete Miete', body: 'Aktive Verträge erzeugen die Perioden, die eingehen sollten.' },
      { title: 'Zahlungsstatus', body: 'Markieren Sie Bezahlt, Ausstehend, Verspätet oder Teilweise.' },
      { title: 'Quittung', body: 'Ist die Miete bezahlt, erzeugen Sie ein PDF und senden Sie es.' },
    ],
    sideTitle: 'Im selben Arbeitsbereich',
    side: [
      { title: 'Ausgaben', body: 'Betrag, Datum, Kategorie, Anbieter und Objekt.' },
      { title: 'Instandhaltung', body: 'Priorität, Status, Anbieter und Kosten — dann in eine Ausgabe wandeln.' },
      { title: 'Dokumente', body: 'Dateien hochladen und Objekt, Mieter oder Vertrag zuordnen.' },
    ],
  },
  rent: {
    h2: 'Sehen, wo jede Miete steht',
    body: 'Rentelyo verfolgt Miete im Arbeitsbereich. Sie erfassen Zahlungen selbst; das Produkt verarbeitet keine Mietzahlungen der Mieter.',
    points: [
      'Erwartete Perioden aus aktiven Verträgen',
      'Status Bezahlt, Ausstehend, Verspätet und Teilweise',
      'Verlauf jeder Periode',
      'Erinnerungen für fällige und überfällige Mieten',
      'PDF-Quittungen, optional per E-Mail',
    ],
  },
  leases: {
    h2: 'Vertragsdaten sollen keine Überraschung sein',
    body: 'Der Vertrag hält Daten und Beträge, die Sie brauchen. Anpassungen werden erst nach Ihrer Bestätigung angewendet. Rentelyo verlängert nicht automatisch und sammelt keine E-Signaturen.',
    points: [
      'Beginn und Ende',
      'Miete, Nebenkosten und Kaution',
      'Zahlungsrhythmus',
      'Ablaufhinweise',
      'Mietanpassungen erst nach Bestätigung',
    ],
  },
  costs: {
    h2: 'Die laufenden Kosten Ihrer Vermietungen verstehen',
    expensesTitle: 'Ausgaben',
    expensesBody: 'Sehen, was jedes Objekt kostet, ohne ein zweites Kostenblatt.',
    expensesPoints: ['Objekt', 'Kategorie', 'Anbieter', 'Betrag', 'Datum', 'Beschreibung', 'Summen'],
    maintenanceTitle: 'Instandhaltung',
    maintenanceBody: 'Erfassen Sie Arbeiten, die Sie als Vermieter beauftragen. Mieter stellen in Rentelyo keine Anfragen.',
    maintenancePoints: ['Objekt', 'Priorität', 'Status', 'Anbieter', 'Kosten', 'Kosten in eine Ausgabe wandeln'],
  },
  documents: {
    h2: 'Wichtige Unterlagen dort ablegen, wo sie hingehören',
    body: 'Laden Sie vorhandene Dateien hoch. Rentelyo speichert sie bei der Vermietung. Es erzeugt keine Verträge und sammelt keine E-Signaturen.',
    points: [
      'Sicherer Upload',
      'Kategorien',
      'Zuordnung zum Objekt',
      'Optionale Zuordnung zum Mieter',
      'Optionale Zuordnung zum Vertrag',
      'Herunterladen oder löschen',
    ],
  },
  dashboard: {
    h2: 'Den Stand Ihrer Vermietungen auf einen Blick',
    body: 'Das Dashboard zeigt den Betrieb: wie viele Objekte, welche vermietet sind, wo Miete und Kosten stehen. Keine Bewertung, keine Rendite, keine Steuerbuchhaltung.',
    metrics: [
      'Objekte gesamt',
      'Vermietet und verfügbar',
      'Erwartete Miete',
      'Eingegangen',
      'Ausstehend',
      'Überfällig',
      'Ausgaben',
      'Netto-Cashflow',
    ],
  },
  fit: {
    h2: 'Für Vermieter gebaut, nicht für eine Verwaltungsabteilung',
    body: 'Unterschiedliche Nutzer brauchen unterschiedliche Werkzeuge. Wer selbst verwaltet, braucht selten die Organisationsschichten größerer Betriebe.',
    leftTitle: 'Komplexität, die Sie oft nicht brauchen',
    left: [
      'Workflows großer Teams',
      'Komplexe Organisationsstrukturen',
      'Unternehmensprozesse',
      'Unnötige Verwaltungsschichten',
    ],
    rightTitle: 'Was Rentelyo liefert',
    right: [
      'Objektdaten',
      'Mieterdaten',
      'Verträge',
      'Mietverfolgung',
      'Ausgaben',
      'Instandhaltung',
      'Dokumente',
      'Erinnerungen',
      'Ein klares Dashboard',
    ],
  },
  grow: {
    h2: 'Mit dem ersten Objekt starten. Wachsen, wenn es nötig ist.',
    body: 'Der kostenlose Tarif umfasst ein Objekt und einen Mieter. Smart deckt derzeit bis zu fünf Objekte, Premium bis zu fünfzehn. Die aktuellen Grenzen stehen auf der Preisseite.',
    plan: 'Keine Karte zum Start. Wechseln Sie nur, wenn Sie mehr Platz brauchen.',
    cta: 'Preise ansehen',
  },
  why: {
    h2: 'Warum kleine Vermieter Software nutzen',
    items: [
      { title: 'Organisiert bleiben', body: 'Objekt, Person und Datei finden, ohne drei Orte zu öffnen.' },
      { title: 'Fristen sehen', body: 'Vertragsende sowie fällige oder überfällige Mieten bleiben sichtbar.' },
      { title: 'Cashflow verstehen', body: 'Erwartet, eingegangen, verspätet und Kosten je Objekt — Betriebskennzahlen, keine Prognosen.' },
      { title: 'Unterlagen an einem Ort', body: 'Verträge, Quittungen, Rechnungen und Belege bei der Vermietung.' },
    ],
  },
  faq: {
    h2: 'Häufige Fragen',
    items: [
      {
        q: 'Was ist Immobilienverwaltung für kleine Vermieter?',
        a: 'Software, die selbst verwaltenden Vermietern hilft, ein kleines Portfolio zu führen: Objekte, Mieter, Verträge, Mietverfolgung, Ausgaben, Instandhaltung und Dokumente — ohne die Schichten eines Unternehmenssystems.',
      },
      {
        q: 'Für wen ist Rentelyo gedacht?',
        a: 'Für unabhängige Vermieter, die bereits Objekte und Mieter haben und selbst verwalten. Es ist keine Plattform für Verwaltungsabteilungen, Agenturen oder Teams.',
      },
      {
        q: 'Eignet sich Rentelyo für nur ein Objekt?',
        a: 'Ja. Der kostenlose Tarif umfasst derzeit ein Objekt und einen Mieter. Bezahlte Tarife erhöhen die Grenzen, wenn das Portfolio wächst.',
      },
      {
        q: 'Kann ich mehrere Objekte mit Rentelyo verwalten?',
        a: 'Ja, im Rahmen Ihres Tarifs. Smart deckt derzeit bis zu fünf Objekte, Premium bis zu fünfzehn. Genaue Grenzen stehen auf der Preisseite.',
      },
      {
        q: 'Kann ich Mieter und Verträge verwalten?',
        a: 'Ja. Sie speichern Kontakte, ordnen Mieter Objekten zu und erfassen Verträge mit Daten, Miete, Nebenkosten, Kaution und Rhythmus.',
      },
      {
        q: 'Verfolgt Rentelyo erwartete Miete automatisch?',
        a: 'Ja. Aktive Verträge erzeugen erwartete Perioden. Sie erfassen dann jede Zahlung und folgen dem Status.',
      },
      {
        q: 'Erkennt Rentelyo verspätete Miete?',
        a: 'Ja. Jede Periode kann Bezahlt, Ausstehend, Verspätet oder Teilweise sein, damit Überfälliges sichtbar bleibt.',
      },
      {
        q: 'Zieht Rentelyo die Miete der Mieter online ein?',
        a: 'Nein. Rentelyo hilft derzeit, Zahlungen zu verfolgen und zu erfassen. Es verarbeitet keine Mietzahlungen online.',
      },
      {
        q: 'Kann ich Ausgaben zum Objekt erfassen?',
        a: 'Ja. Erfassen Sie Betrag, Datum, Kategorie, Anbieter, Beschreibung und Objekt und folgen Sie den Summen.',
      },
      {
        q: 'Kann ich Instandhaltung verwalten?',
        a: 'Ja. Legen Sie einen Datensatz mit Priorität, Status, Anbieter und Kosten an und wandeln Sie Kosten in eine Ausgabe. Vermieter tragen diese Fälle ein.',
      },
      {
        q: 'Kann ich Mietunterlagen speichern?',
        a: 'Ja. Laden Sie Dateien hoch, kategorisieren Sie sie, ordnen Sie sie einem Objekt und optional Mieter oder Vertrag zu. Keine E-Signatur, keine erzeugten Verträge.',
      },
      {
        q: 'Kann Rentelyo PDF-Mietquittungen erzeugen?',
        a: 'Ja. Ist die Miete als bezahlt markiert, können Sie ein PDF erzeugen und per E-Mail senden.',
      },
      {
        q: 'Brauche ich Software, wenn ich nur wenige Vermietungen habe?',
        a: 'Nicht unbedingt ein Unternehmenssystem. Schon wenige Vermietungen erzeugen Daten, erwartete Miete, Ausgaben, Reparaturen und Dateien. Rentelyo verbindet diese Arbeit ohne Abteilungsprozesse.',
      },
      {
        q: 'Ist Rentelyo eine Inserate-Website?',
        a: 'Nein. Rentelyo ist Verwaltungssoftware für Vermieter, die bereits Mieter haben. Keine Inserate, kein Marktplatz, kein Service zur Mietergewinnung.',
      },
    ],
  },
  finalCta: {
    h2: 'Einfache Verwaltung für Ihr Mietportfolio',
    body: 'Halten Sie Objekte, Mieter, Verträge, Miete und Unterlagen organisiert — ohne unnötige Komplexität.',
    primary: 'Kostenlos starten',
    secondary: 'Preise ansehen',
  },
};

export const smallLandlordPt: typeof smallLandlordEn = {
  moreLabel: 'Explorar também',
  relatedPmsLead: 'Quer a visão operacional mais ampla? Veja a Rentelyo como',
  relatedPmsAnchor: 'software de gestão de arrendamentos para senhorios',
  relatedPmsTail: '.',
  relatedSimpleLead: 'Vem de folhas e pastas? Comece pelo',
  relatedSimpleAnchor: 'software para senhorios',
  relatedSimpleTail: '.',
  hero: {
    kicker: 'Para pequenos senhorios',
    h1: 'Software de gestão de arrendamentos para pequenos senhorios',
    lede: 'Gira imóveis, inquilinos, contratos, rendas, despesas, manutenção e documentos num espaço simples — sem a complexidade do software empresarial.',
    primary: 'Começar grátis',
    secondary: 'Ver preços',
    note: 'Sem cartão de crédito',
  },
  problem: {
    h2: 'Não precisa de software de empresa para poucos arrendamentos',
    body: 'Um senhorio pequeno continua a ter trabalho real: imóveis, inquilinos, datas de contrato, renda esperada, atrasos, despesas, reparações e documentos. Muitos sistemas profissionais acrescentam fluxos de equipa pensados para operações maiores. A Rentelyo liga o essencial: tudo o que precisa para gerir os arrendamentos, sem complexidade empresarial.',
    needs: ['Imóveis', 'Inquilinos', 'Datas de contrato', 'Renda esperada', 'Atrasos', 'Despesas', 'Reparações', 'Documentos'],
  },
  essentials: {
    h2: 'O essencial para gerir a carteira de arrendamento',
    lede: 'São as ferramentas que um senhorio que se gere sozinho realmente usa — não um mapa de processos de um departamento.',
    cards: [
      { title: 'Imóveis', body: 'Mantenha a informação de cada arrendamento organizada.' },
      { title: 'Inquilinos', body: 'Reúna fichas e contactos.' },
      { title: 'Contratos', body: 'Acompanhe prazos, datas, renda, encargos e vencimentos.' },
      { title: 'Renda', body: 'Saiba o que está esperado, pago, pendente ou atrasado.' },
      { title: 'Despesas', body: 'Registe cada custo no imóvel certo.' },
      { title: 'Manutenção', body: 'Acompanhe trabalhos, prioridade, fornecedor, estado e custo.' },
      { title: 'Documentos', body: 'Guarde ficheiros e associe-os às fichas certas.' },
    ],
  },
  chain: {
    h2: 'Do imóvel ao pagamento, tudo ligado',
    lede: 'Cada ficha alimenta a seguinte, sem reconstruir a história a partir de ficheiros soltos.',
    steps: [
      { title: 'Imóvel', body: 'Adicione o arrendamento e guarde os dados numa ficha.' },
      { title: 'Inquilino', body: 'Guarde o contacto e ligue a pessoa a esse imóvel.' },
      { title: 'Contrato', body: 'Registe datas, renda, encargos, caução e frequência no mesmo contrato.' },
      { title: 'Renda esperada', body: 'Os contratos ativos geram os períodos a receber.' },
      { title: 'Estado do pagamento', body: 'Marque Pago, Pendente, Atrasado ou Parcial.' },
      { title: 'Recibo', body: 'Quando a renda está paga, gere um PDF e envie-o.' },
    ],
    sideTitle: 'No mesmo espaço',
    side: [
      { title: 'Despesas', body: 'Montante, data, categoria, fornecedor e imóvel.' },
      { title: 'Manutenção', body: 'Prioridade, estado, fornecedor e custo — depois converta o custo numa despesa.' },
      { title: 'Documentos', body: 'Carregue ficheiros e associe-os ao imóvel, inquilino ou contrato.' },
    ],
  },
  rent: {
    h2: 'Saiba onde está cada renda',
    body: 'A Rentelyo acompanha a renda no espaço de trabalho. Você regista os pagamentos; o produto não processa os pagamentos dos inquilinos.',
    points: [
      'Períodos esperados a partir de contratos ativos',
      'Estados Pago, Pendente, Atrasado e Parcial',
      'Histórico de cada período',
      'Lembretes próximos e em atraso',
      'Recibos PDF, com envio por e-mail',
    ],
  },
  leases: {
    h2: 'Para as datas de contrato não serem uma surpresa',
    body: 'O contrato guarda as datas e valores a vigiar. Os aumentos são acompanhados e aplicados só depois da sua confirmação. A Rentelyo não renova automaticamente nem recolhe assinaturas eletrónicas.',
    points: [
      'Datas de início e fim',
      'Renda, encargos e caução',
      'Frequência de pagamento',
      'Alertas de termo',
      'Acompanhamento de revisões, aplicadas após confirmação',
    ],
  },
  costs: {
    h2: 'Perceba o custo do dia a dia dos arrendamentos',
    expensesTitle: 'Despesas',
    expensesBody: 'Veja o que cada imóvel custa, sem um segundo livro de custos.',
    expensesPoints: ['Imóvel', 'Categoria', 'Fornecedor', 'Montante', 'Data', 'Descrição', 'Totais'],
    maintenanceTitle: 'Manutenção',
    maintenanceBody: 'Registe os trabalhos que organiza. Os inquilinos não submetem pedidos na Rentelyo.',
    maintenancePoints: ['Imóvel', 'Prioridade', 'Estado', 'Fornecedor', 'Custo', 'Converter o custo numa despesa'],
  },
  documents: {
    h2: 'Guarde os documentos de arrendamento no sítio certo',
    body: 'Carregue os ficheiros que já tem. A Rentelyo guarda-os junto do arrendamento. Não gera contratos nem recolhe assinaturas eletrónicas.',
    points: [
      'Carregamento seguro',
      'Categorias',
      'Associação a um imóvel',
      'Associação opcional a um inquilino',
      'Associação opcional a um contrato',
      'Descarregar ou eliminar',
    ],
  },
  dashboard: {
    h2: 'Veja a saúde dos arrendamentos de relance',
    body: 'O painel é visibilidade operacional: quantos imóveis tem, quais estão arrendados e onde estão rendas e custos. Não é avaliação, rendimento nem fiscalidade.',
    metrics: [
      'Total de imóveis',
      'Arrendados e disponíveis',
      'Renda esperada',
      'Recebida',
      'Pendente',
      'Em atraso',
      'Despesas',
      'Fluxo líquido',
    ],
  },
  fit: {
    h2: 'Feito para senhorios, não para um departamento de gestão',
    body: 'Utilizadores diferentes precisam de ferramentas diferentes. Quem se gere sozinho raramente precisa das camadas organizacionais de operações maiores.',
    leftTitle: 'Complexidade de que pode não precisar',
    left: [
      'Fluxos de equipas grandes',
      'Estruturas organizacionais complexas',
      'Processos de empresa',
      'Camadas administrativas desnecessárias',
    ],
    rightTitle: 'O que a Rentelyo lhe dá',
    right: [
      'Fichas de imóveis',
      'Fichas de inquilinos',
      'Contratos',
      'Acompanhamento de rendas',
      'Despesas',
      'Manutenção',
      'Documentos',
      'Lembretes',
      'Um painel claro',
    ],
  },
  grow: {
    h2: 'Comece com o primeiro imóvel. Cresça quando precisar.',
    body: 'O plano gratuito inclui um imóvel e um inquilino. Depois, o Smart cobre hoje até cinco imóveis e o Premium até quinze. Consulte sempre a página de preços para a configuração atual.',
    plan: 'Sem cartão para começar. Passe a um plano pago só quando precisar de mais espaço.',
    cta: 'Ver preços',
  },
  why: {
    h2: 'Porque um pequeno senhorio usa software',
    items: [
      { title: 'Manter-se organizado', body: 'Encontre o imóvel, a pessoa e o ficheiro sem abrir três sítios.' },
      { title: 'Apanhar os prazos', body: 'Termos de contrato e rendas próximas ou em atraso continuam visíveis.' },
      { title: 'Perceber o fluxo do arrendamento', body: 'Veja o esperado, o recebido, o atrasado e o custo de cada imóvel — números operacionais, não previsões.' },
      { title: 'Registos num só sítio', body: 'Contratos, recibos, faturas e comprovativos junto do arrendamento.' },
    ],
  },
  faq: {
    h2: 'Perguntas frequentes',
    items: [
      {
        q: 'O que é software de gestão de arrendamentos para pequenos senhorios?',
        a: 'É uma ferramenta que ajuda senhorios que se gerem sozinhos a conduzir uma carteira pequena: imóveis, inquilinos, contratos, acompanhamento de rendas, despesas, manutenção e documentos, sem as camadas de um sistema empresarial.',
      },
      {
        q: 'Para quem é a Rentelyo?',
        a: 'Para senhorios independentes que já têm imóveis e inquilinos e querem gerir sozinhos. Não é uma plataforma para um departamento de gestão, uma agência ou uma equipa.',
      },
      {
        q: 'A Rentelyo serve com um só imóvel?',
        a: 'Sim. O plano gratuito inclui hoje um imóvel e um inquilino. Os planos pagos aumentam esses limites se a carteira crescer.',
      },
      {
        q: 'Posso gerir vários imóveis com a Rentelyo?',
        a: 'Sim, dentro do seu plano. O Smart cobre hoje até cinco imóveis; o Premium até quinze. Os limites exatos estão na página de preços.',
      },
      {
        q: 'Posso gerir inquilinos e contratos?',
        a: 'Sim. Guarde contactos, associe inquilinos a imóveis e registe contratos com datas, renda, encargos, caução e frequência.',
      },
      {
        q: 'A Rentelyo acompanha automaticamente a renda esperada?',
        a: 'Sim. Os contratos ativos geram períodos esperados. Depois regista cada pagamento e acompanha o estado.',
      },
      {
        q: 'A Rentelyo identifica rendas em atraso?',
        a: 'Sim. Cada período pode ser Pago, Pendente, Atrasado ou Parcial, para os atrasos não se perderem.',
      },
      {
        q: 'A Rentelyo cobra a renda do inquilino online?',
        a: 'Não. A Rentelyo ajuda atualmente a acompanhar e registar pagamentos. Não processa os pagamentos dos inquilinos online.',
      },
      {
        q: 'Posso registar as despesas do imóvel?',
        a: 'Sim. Registe montante, data, categoria, fornecedor, descrição e imóvel, e acompanhe os totais.',
      },
      {
        q: 'Posso gerir a manutenção?',
        a: 'Sim. Crie um registo com prioridade, estado, fornecedor e custo, e converta um custo numa despesa. O senhorio introduz estes trabalhos.',
      },
      {
        q: 'Posso guardar documentos de arrendamento?',
        a: 'Sim. Carregue, categorize, associe a um imóvel e, se quiser, a um inquilino ou contrato. Sem assinatura eletrónica nem contratos gerados.',
      },
      {
        q: 'A Rentelyo pode gerar recibos PDF?',
        a: 'Sim. Quando a renda é marcada como paga, pode gerar um recibo PDF e enviá-lo por e-mail.',
      },
      {
        q: 'Preciso de software se só tenho poucos arrendamentos?',
        a: 'Talvez não um sistema de empresa. Poucos arrendamentos já geram datas, renda esperada, despesas, reparações e ficheiros. A Rentelyo liga esse trabalho sem processos de departamento.',
      },
      {
        q: 'A Rentelyo é um site de anúncios?',
        a: 'Não. É software de gestão para senhorios que já têm inquilinos. Não é um site de anúncios, um marketplace nem um serviço de captação de inquilinos.',
      },
    ],
  },
  finalCta: {
    h2: 'Gestão simples para a sua carteira de arrendamento',
    body: 'Mantenha imóveis, inquilinos, contratos, rendas e registos organizados, sem complexidade desnecessária.',
    primary: 'Começar grátis',
    secondary: 'Ver preços',
  },
};

export const smallLandlordAr: typeof smallLandlordEn = {
  moreLabel: 'استكشف أيضاً',
  relatedPmsLead: 'تريد الصورة التشغيلية الأوسع؟ اطّلع على Rentelyo كـ',
  relatedPmsAnchor: 'برنامج إدارة العقارات للمُلّاك',
  relatedPmsTail: '.',
  relatedSimpleLead: 'قادم من الجداول والمجلدات؟ ابدأ بـ',
  relatedSimpleAnchor: 'برنامج للمُلّاك',
  relatedSimpleTail: '.',
  hero: {
    kicker: 'للمُلّاك الصغار',
    h1: 'برنامج إدارة عقارات للمُلّاك الصغار',
    lede: 'أدِر عقاراتك ومستأجريك وعقودك والإيجار والمصاريف والصيانة والمستندات في مساحة بسيطة — دون تعقيد أنظمة المؤسسات.',
    primary: 'ابدأ مجاناً',
    secondary: 'عرض الأسعار',
    note: 'لا حاجة لبطاقة ائتمان',
  },
  problem: {
    h2: 'لا تحتاج برنامجاً مؤسسياً لإدارة بضع وحدات مؤجرة',
    body: 'حتى المالك الصغير لديه عمل تشغيلي حقيقي: عقارات، مستأجرون، تواريخ عقود، إيجار متوقع، تأخيرات، مصاريف، إصلاحات ومستندات. كثير من الأنظمة المهنية تضيف مسارات فرق صُممت لعمليات أكبر. تربط Rentelyo الأساسيات: كل ما تحتاجه لإدارة إيجاراتك، دون تعقيد المؤسسات.',
    needs: ['العقارات', 'المستأجرون', 'تواريخ العقود', 'الإيجار المتوقع', 'التأخيرات', 'المصاريف', 'الإصلاحات', 'المستندات'],
  },
  essentials: {
    h2: 'الأساسيات لإدارة محفظة الإيجار',
    lede: 'هذه الأدوات التي يستخدمها المالك الذي يدير بنفسه فعلاً — وليست خريطة عمليات لقسم كامل.',
    cards: [
      { title: 'العقارات', body: 'أبقِ معلومات كل إيجار منظَّمة.' },
      { title: 'المستأجرون', body: 'اجمع السجلات وبيانات الاتصال.' },
      { title: 'العقود', body: 'تابع الشروط والتواريخ والإيجار والرسوم والمواعيد.' },
      { title: 'الإيجار', body: 'اعرف ما هو متوقع أو مدفوع أو معلّق أو متأخر.' },
      { title: 'المصاريف', body: 'سجّل كل تكلفة على العقار الصحيح.' },
      { title: 'الصيانة', body: 'تابع الأعمال والأولوية والمورّد والحالة والتكلفة.' },
      { title: 'المستندات', body: 'اخزن الملفات واربطها بالسجلات الصحيحة.' },
    ],
  },
  chain: {
    h2: 'من العقار إلى الدفع، كل شيء متصل',
    lede: 'كل سجل يغذي التالي، دون إعادة بناء القصة من ملفات منفصلة.',
    steps: [
      { title: 'العقار', body: 'أضف الإيجار واحفظ تفاصيله في سجل واحد.' },
      { title: 'المستأجر', body: 'احفظ الاتصال واربط الشخص بذلك العقار.' },
      { title: 'العقد', body: 'سجّل التواريخ والإيجار والرسوم والتأمين والتكرار على العقد نفسه.' },
      { title: 'الإيجار المتوقع', body: 'تنشئ العقود النشطة الفترات التي يُفترض قبضها.' },
      { title: 'حالة الدفع', body: 'علّم مدفوع أو معلّق أو متأخر أو جزئي.' },
      { title: 'الإيصال', body: 'عندما يُعلَّم الإيجار مدفوعاً، أنشئ PDF وأرسله.' },
    ],
    sideTitle: 'في المساحة نفسها',
    side: [
      { title: 'المصاريف', body: 'المبلغ والتاريخ والفئة والمورّد والعقار.' },
      { title: 'الصيانة', body: 'الأولوية والحالة والمورّد والتكلفة — ثم حوّل التكلفة إلى مصروف.' },
      { title: 'المستندات', body: 'ارفع الملفات واربطها بالعقار أو المستأجر أو العقد.' },
    ],
  },
  rent: {
    h2: 'اعرف أين يقف كل إيجار',
    body: 'تتابع Rentelyo الإيجار في مساحة العمل. أنت تسجّل المدفوعات؛ المنتج لا يعالج مدفوعات المستأجرين.',
    points: [
      'فترات متوقعة من العقود النشطة',
      'حالات مدفوع ومعلّق ومتأخر وجزئي',
      'سجل كل فترة',
      'تذكيرات قادمة ومتأخرة',
      'إيصالات PDF مع خيار الإرسال بالبريد',
    ],
  },
  leases: {
    h2: 'حتى لا تصبح تواريخ العقد مفاجأة',
    body: 'يحمل العقد التواريخ والمبالغ التي تحتاج متابعتها. تُطبَّق الزيادات بعد تأكيدك فقط. لا تجدّد Rentelyo تلقائياً ولا تجمع توقيعات إلكترونية.',
    points: [
      'تاريخا البداية والنهاية',
      'الإيجار والرسوم والتأمين',
      'تكرار الدفع',
      'تنبيهات الانتهاء',
      'متابعة المراجعات بعد التأكيد',
    ],
  },
  costs: {
    h2: 'افهم التكلفة اليومية لإيجاراتك',
    expensesTitle: 'المصاريف',
    expensesBody: 'اعرف ما يكلّفه كل عقار دون دفتر تكاليف ثانٍ.',
    expensesPoints: ['العقار', 'الفئة', 'المورّد', 'المبلغ', 'التاريخ', 'الوصف', 'المجاميع'],
    maintenanceTitle: 'الصيانة',
    maintenanceBody: 'سجّل الأعمال التي تنظّمها كمالك. لا يقدّم المستأجرون طلبات داخل Rentelyo.',
    maintenancePoints: ['العقار', 'الأولوية', 'الحالة', 'المورّد', 'التكلفة', 'تحويل التكلفة إلى مصروف'],
  },
  documents: {
    h2: 'أبقِ مستندات الإيجار حيث تنتمي',
    body: 'ارفع الملفات الموجودة لديك. تخزنها Rentelyo بجانب الإيجار. لا تنشئ عقوداً ولا تجمع توقيعات إلكترونية.',
    points: [
      'رفع آمن',
      'تصنيفات',
      'ربط بعقار',
      'ربط اختياري بمستأجر',
      'ربط اختياري بعقد',
      'تنزيل أو حذف',
    ],
  },
  dashboard: {
    h2: 'اطّلع على صحة إيجاراتك بنظرة واحدة',
    body: 'لوحة التحكم رؤية تشغيلية: عدد العقارات، أيها مؤجر، وأين يقف الإيجار والتكاليف. ليست تقييماً ولا عائداً ولا محاسبة ضريبية.',
    metrics: [
      'إجمالي العقارات',
      'مؤجرة ومتاحة',
      'الإيجار المتوقع',
      'المحصّل',
      'المعلّق',
      'المتأخر',
      'المصاريف',
      'صافي التدفق',
    ],
  },
  fit: {
    h2: 'مصمَّم للمُلّاك لا لأقسام إدارة العقارات',
    body: 'يحتاج المستخدمون أدوات مختلفة. من يدير بنفسه نادراً ما يحتاج طبقات تنظيمية صُممت لعمليات أكبر.',
    leftTitle: 'تعقيد قد لا تحتاجه',
    left: [
      'مسارات فرق كبيرة',
      'هياكل تنظيمية معقّدة',
      'عمليات مؤسسية',
      'طبقات إدارية زائدة',
    ],
    rightTitle: 'ما تقدّمه Rentelyo',
    right: [
      'سجلات العقارات',
      'سجلات المستأجرين',
      'العقود',
      'متابعة الإيجار',
      'المصاريف',
      'الصيانة',
      'المستندات',
      'التذكيرات',
      'لوحة تحكم واضحة',
    ],
  },
  grow: {
    h2: 'ابدأ بعقارك الأول. توسّع عندما تحتاج.',
    body: 'تشمل الخطة المجانية عقاراً واحداً ومستأجراً واحداً. بعد ذلك تغطي Smart حالياً حتى خمسة عقارات وPremium حتى خمسة عشر. راجع صفحة الأسعار دائماً للحدود الحالية.',
    plan: 'بلا بطاقة للبدء. انتقل إلى خطة مدفوعة فقط عندما تحتاج مساحة إضافية.',
    cta: 'عرض الأسعار',
  },
  why: {
    h2: 'لماذا يستخدم المالك الصغير برنامجاً',
    items: [
      { title: 'البقاء منظَّماً', body: 'اعثر على العقار والشخص والملف دون فتح ثلاثة أماكن.' },
      { title: 'التقاط المواعيد', body: 'انتهاء العقود والإيجار القادم أو المتأخر يبقى ظاهراً.' },
      { title: 'فهم تدفق الإيجار', body: 'شاهد المتوقع والمحصّل والمتأخر وتكلفة كل عقار — أرقام تشغيلية لا توقعات.' },
      { title: 'السجلات في مكان واحد', body: 'العقود والإيصالات والفواتير والإثباتات بجانب الإيجار.' },
    ],
  },
  faq: {
    h2: 'أسئلة شائعة',
    items: [
      {
        q: 'ما هو برنامج إدارة العقارات للمُلّاك الصغار؟',
        a: 'أداة تساعد المُلّاك الذين يديرون بأنفسهم على تشغيل محفظة صغيرة: عقارات ومستأجرون وعقود ومتابعة إيجار ومصاريف وصيانة ومستندات، دون طبقات نظام مؤسسي.',
      },
      {
        q: 'لمن صُممت Rentelyo؟',
        a: 'للمُلّاك المستقلين الذين لديهم عقارات ومستأجرون ويريدون الإدارة بأنفسهم. ليست منصة لأقسام إدارة أو وكالات أو فرق.',
      },
      {
        q: 'هل تناسب Rentelyo مالكاً بعقار واحد؟',
        a: 'نعم. تشمل الخطة المجانية حالياً عقاراً واحداً ومستأجراً واحداً. تزيد الخطط المدفوعة هذه الحدود مع نمو المحفظة.',
      },
      {
        q: 'هل يمكنني إدارة عدة عقارات مع Rentelyo؟',
        a: 'نعم ضمن خطتك. تغطي Smart حالياً حتى خمسة عقارات وPremium حتى خمسة عشر. الحدود الدقيقة في صفحة الأسعار.',
      },
      {
        q: 'هل يمكنني إدارة المستأجرين والعقود؟',
        a: 'نعم. احفظ جهات الاتصال، اربط المستأجرين بالعقارات، وسجّل العقود مع التواريخ والإيجار والرسوم والتأمين والتكرار.',
      },
      {
        q: 'هل تتابع Rentelyo الإيجار المتوقع تلقائياً؟',
        a: 'نعم. تنشئ العقود النشطة فترات متوقعة. ثم تسجّل كل دفعة وتتابع حالتها.',
      },
      {
        q: 'هل تميّز Rentelyo الإيجار المتأخر؟',
        a: 'نعم. يمكن لكل فترة أن تكون مدفوعاً أو معلّقاً أو متأخراً أو جزئياً، فيبقى التأخير ظاهراً.',
      },
      {
        q: 'هل تحصّل Rentelyo إيجار المستأجر عبر الإنترنت؟',
        a: 'لا. تساعد Rentelyo حالياً على تتبع وتسجيل المدفوعات. ولا تعالج مدفوعات المستأجرين عبر الإنترنت.',
      },
      {
        q: 'هل يمكنني تتبع مصاريف العقار؟',
        a: 'نعم. سجّل المبلغ والتاريخ والفئة والمورّد والوصف والعقار، ثم تابع المجاميع.',
      },
      {
        q: 'هل يمكنني إدارة صيانة العقار؟',
        a: 'نعم. أنشئ سجلاً بالأولوية والحالة والمورّد والتكلفة، وحوّل التكلفة إلى مصروف. يُدخل المالك هذه الأعمال.',
      },
      {
        q: 'هل يمكنني تخزين مستندات الإيجار؟',
        a: 'نعم. ارفع وصنّف واربط بعقار واختيارياً بمستأجر أو عقد. لا توقيع إلكتروني ولا عقود مولَّدة.',
      },
      {
        q: 'هل يمكن لـ Rentelyo إنشاء إيصالات PDF؟',
        a: 'نعم. عندما يُعلَّم الإيجار مدفوعاً، يمكنك إنشاء إيصال PDF وإرساله بالبريد.',
      },
      {
        q: 'هل أحتاج برنامجاً إذا كان لدي بضع وحدات فقط؟',
        a: 'قد لا تحتاج نظاماً مؤسسياً. بضع وحدات تنتج تواريخ وإيجاراً متوقعاً ومصاريف وإصلاحات وملفات. تربط Rentelyo هذا العمل دون عمليات قسم.',
      },
      {
        q: 'هل Rentelyo موقع إعلانات عقارية؟',
        a: 'لا. هو برنامج إدارة للمُلّاك الذين لديهم مستأجرون بالفعل. ليس موقع إعلانات ولا سوقاً ولا خدمة لاكتساب مستأجرين.',
      },
    ],
  },
  finalCta: {
    h2: 'إدارة بسيطة لمحفظة إيجارك',
    body: 'أبقِ العقارات والمستأجرين والعقود والإيجار والسجلات منظَّمة دون تعقيد زائد.',
    primary: 'ابدأ مجاناً',
    secondary: 'عرض الأسعار',
  },
};
